workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 30
    instance_type: mac_mini_m2
    working_directory: mobile_app
    environment:
      flutter: stable
      android_signing: false
    scripts:
      - name: Flutter clean
        script: |
          flutter clean
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Generate code (build_runner)
        script: |
          dart run build_runner build --delete-conflicting-outputs
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
