workflows:
  android-apk-build:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: mobile_app
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          cd mobile_app && flutter pub get
      - name: Build APK
        script: |
          cd mobile_app && flutter build apk --release -t lib/main.dart
    artifacts:
      - mobile_app/build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/flutter-apk/app-release.apk
