# Generated by Django 6.0.7 on 2026-07-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم العميل')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد الحساب (الشكك)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المورد')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='الشركة')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد المورد')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('transaction_type', models.CharField(choices=[('sale_credit', 'فاتورة مبيعات شكك (آجل)'), ('purchase_credit', 'فاتورة مشتريات آجل'), ('pay_received', 'دفعة مستلمة من العميل'), ('pay_sent', 'دفعة مسددة للمورد')], max_length=30, verbose_name='نوع المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='ledger.customer', verbose_name='العميل')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='ledger.supplier', verbose_name='المورد')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
