# Generated by Django 6.0.7 on 2026-07-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='البيان / الملاحظات'),
        ),
    ]
