# Generated by Django 6.0.7 on 2026-07-29 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_add_notes_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان / المنطقة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customers/', verbose_name='صورة العميل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات وتفاصيل إضافية'),
        ),
        migrations.AddField(
            model_name='customer',
            name='workplace',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مكان العمل / المزرعة / الورشة'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان / المقر'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/', verbose_name='صورة المورد'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات وتفاصيل إضافية'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
