# Generated by Django 6.0.7 on 2026-08-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_add_customer_and_supplier_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='موعد استحقاق السداد'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='موعد استحقاق السداد'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='موعد استحقاق السداد'),
        ),
    ]
