# Generated by Django 6.0.7 on 2026-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_transaction_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد الحساب (الشكك)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='موعد استحقاق السداد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='موعد استحقاق السداد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='اسم المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='موعد استحقاق السداد'),
        ),
    ]
