# Generated by Django 5.0.14 on 2026-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_customer_balance_alter_customer_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale_credit', 'فاتورة مبيعات شكك (آجل)'), ('purchase_credit', 'فاتورة مشتريات آجل'), ('pay_received', 'دفعة مستلمة من العميل'), ('pay_sent', 'دفعة مسددة للمورد'), ('cash_deposit', 'إيداع نقدي / إنعاش الخزينة'), ('cash_withdraw', 'سحب نقدي من الخزينة')], max_length=30, verbose_name='نوع المعاملة'),
        ),
    ]
