# Generated by Django 6.0.7 on 2026-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'إيجار المحل'), ('utility', 'فواتير (كهرباء / مياه / إنترنت)'), ('salary', 'رواتب وأجور الموظفين'), ('marketing', 'تسويق وإعلانات'), ('other', 'مصروفات تشغيلية أخرى')], db_index=True, default='other', max_length=30, verbose_name='نوع المصروف')),
                ('description', models.CharField(max_length=255, verbose_name='بيان المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
