# Generated by Django 6.0.7 on 2026-08-10 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة / المؤسسة')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='معرف النظام (URL)')),
                ('plan', models.CharField(choices=[('trial', 'تجربة مجانية'), ('basic', 'الباقة الأساسية'), ('pro', 'الباقة الاحترافية')], default='trial', max_length=20, verbose_name='الباقة')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية فترة التجربة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف التواصل')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'شركة / مؤسسة',
                'verbose_name_plural': 'الشركات والمؤسسات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مسؤول النظام'), ('manager', 'مدير'), ('cashier', 'كاشير / موظف مبيعات'), ('viewer', 'مشاهد فقط')], default='cashier', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
