# Generated by Django 6.0.7 on 2026-09-09 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google Sub/ID')),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني لحساب Google')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الربط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_auth', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ربط حساب اجتماعي',
                'verbose_name_plural': 'ربط الحسابات الاجتماعية',
            },
        ),
    ]
