# Generated by Django 5.0.14 on 2026-09-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_usersocialauth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='شعار المحل / الشركة'),
        ),
    ]
