# Generated by Django 5.0.14 on 2026-09-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='logo',
        ),
    ]
