# Generated by Django 5.0.14 on 2026-09-16 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_remove_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display', models.CharField(max_length=150, verbose_name='اسم الموظف أو المستخدم')),
                ('user_email', models.CharField(blank=True, default='', max_length=150, verbose_name='البريد الإلكتروني')),
                ('module', models.CharField(choices=[('pos', 'المبيعات ونقاط البيع'), ('inventory', 'المخزن والمنتجات'), ('purchase_orders', 'طلبات البضاعة والنواقص'), ('maintenance', 'الورشة والصيانة'), ('ledger', 'العملاء والشكك والموردين'), ('expenses', 'المصروفات العامة'), ('cash', 'الخزينة وحركات النقدية'), ('reports', 'التقارير المالية'), ('backup', 'النسخ الاحتياطي والأمان'), ('auth', 'الحسابات وتسجيل الدخول'), ('settings', 'إعدادات النظام'), ('other', 'حركات متنوعة')], db_index=True, max_length=50, verbose_name='القسم')),
                ('action_type', models.CharField(choices=[('create', 'إضافة جديدة'), ('update', 'تعديل بيانات'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('price_change', 'تعديل أسعار'), ('stock_change', 'تعديل مخزون'), ('status_change', 'تغيير حالة'), ('receive_order', 'استلام شحنة بضاعة'), ('export', 'تصدير بيانات'), ('import', 'استيراد بيانات'), ('restore', 'استرجاع نسخة احتياطية'), ('cash_operation', 'حركة خزانة / نقدية'), ('other', 'إجراء آخر')], db_index=True, max_length=50, verbose_name='نوع الإجراء')),
                ('severity', models.CharField(choices=[('info', 'عادي'), ('warning', 'تنبيه'), ('danger', 'حساس / خطير')], db_index=True, default='info', max_length=20, verbose_name='مستوى الأهمية')),
                ('description', models.TextField(verbose_name='وصف الحدث الدقيق')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان الـ IP')),
                ('device_info', models.CharField(blank=True, default='', max_length=200, verbose_name='نوع الجهاز والمتصفح')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='بيانات المتصفح والنظام')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ ووقت الحركة')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant', verbose_name='الشركة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل حركة ونشاط',
                'verbose_name_plural': 'سجل نشاطات وحركات النظام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='dashboard_a_module_3fbe83_idx'), models.Index(fields=['action_type', 'created_at'], name='dashboard_a_action__74c1e7_idx'), models.Index(fields=['severity', 'created_at'], name='dashboard_a_severit_cbd3ff_idx')],
            },
        ),
    ]
