# Generated by Django 6.0.7 on 2026-07-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المنتج')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='رمز SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الباركود')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الشراء')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('min_stock_threshold', models.IntegerField(default=5, verbose_name='الحد الأدنى للتنبيه')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'), models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='رسالة التنبيه')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='تم حلها')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
