# Generated by Django 6.0.7 on 2026-07-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fertilizers', 'أسمدة ومخصبات زراعية'), ('pesticides', 'مبيدات حشرية وفطرية'), ('spare_parts', 'قطع غيار مواقير ورش'), ('equipment', 'معدات وآلات زراعية'), ('oils', 'زيوت وشحومات'), ('general', 'عام / متنوع')], default='general', max_length=50, verbose_name='التصنيف / الفئة'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'),
        ),
    ]
