# Generated by Django 6.0.7 on 2026-07-29 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_image_and_category_to_product'),
        ('ledger', '0003_add_customer_and_supplier_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ledger.supplier', verbose_name='المورد / الشركة الافتراضية'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم طلب البضاعة')),
                ('status', models.CharField(choices=[('draft', 'مسودة (قيد التحضير)'), ('sent', 'تم الإرسال للشركة'), ('received', 'تم استلام البضاعة بالمخزن'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات وتوجيهات للشركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ استلام الشحنة')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='ledger.supplier', verbose_name='الشركة / المورد الرئيسي')),
            ],
            options={
                'verbose_name': 'طلب بضاعة',
                'verbose_name_plural': 'طلبات البضاعة والنواقص',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_item_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم صنف خارجي / تخصيص')),
                ('quantity_requested', models.IntegerField(default=1, verbose_name='الكمية المطلوبة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='تكلفة القطعة التقديرية')),
                ('is_received', models.BooleanField(default=False, verbose_name='تم الاستلام')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='inventory.product', verbose_name='المنتج بالمخزن')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='طلب البضاعة')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='ledger.supplier', verbose_name='الشركة / المورد')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
