# Generated by Django 6.0.7 on 2026-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='عام / متنوع', max_length=100, verbose_name='التصنيف / الفئة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='رمز SKU'),
        ),
    ]
