# Generated by Django 6.0.7 on 2026-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان/بيان الجرد')),
                ('audit_date', models.DateField(auto_now_add=True, verbose_name='تاريخ إجراء الجرد')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='بداية فترة الجرد')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='نهاية فترة الجرد')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي المبيعات')),
                ('cogs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='تكلفة المبيعات')),
                ('maintenance_labor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='أجور الصيانة')),
                ('maintenance_parts_sell', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='مبيعات قطع الغيار')),
                ('maintenance_parts_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='تكلفة قطع الغيار')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المصروفات')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='صافي الربح')),
                ('inventory_cost_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='قيمة المخزون بسعر الشراء')),
                ('inventory_retail_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='قيمة المخزون بسعر البيع')),
                ('customer_debts', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ديون العملاء وقت الجرد')),
                ('supplier_debts', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ديون الموردين وقت الجرد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات وتفاصيل الجرد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
