# Generated by Django 6.0.7 on 2026-07-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الفاتورة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('visa', 'شبكة / فيزا'), ('deferred', 'شكك / آجل')], db_index=True, default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي الفاتورة')),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='تكلفة البضاعة المباعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ledger.customer', verbose_name='العميل')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.product', verbose_name='المنتج')),
            ],
        ),
    ]
