# Generated by Django 6.0.7 on 2026-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_order_tenant_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='رقم الفاتورة'),
        ),
    ]
