# Generated by Django 6.0.7 on 2026-07-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=100, unique=True, verbose_name='رقم تذكرة الصيانة')),
                ('device_name', models.CharField(max_length=200, verbose_name='المعدة / الموتور')),
                ('status', models.CharField(choices=[('pending', 'استلام / قيد الانتظار'), ('in_progress', 'صيانة نشطة'), ('completed', 'جاهز للاستلام'), ('delivered', 'تم التسليم والتحصيل')], db_index=True, default='pending', max_length=30, verbose_name='حالة الصيانة')),
                ('labor_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رسوم المصنعية')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='تكلفة قطع الغيار')),
                ('parts_sell', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='مبيعات قطع الغيار')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ledger.customer', verbose_name='العميل')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketPartConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر المطلوب')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة الفعلية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_parts', to='inventory.product', verbose_name='المنتج (قطعة الغيار)')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_consumed', to='maintenance.maintenanceticket', verbose_name='تذكرة الصيانة')),
            ],
        ),
    ]
