# Generated by Django 6.0.7 on 2026-08-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tenants.tenant', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='ticket_number',
            field=models.CharField(max_length=100, verbose_name='رقم تذكرة الصيانة'),
        ),
    ]
